/**
 * eda-mcp-server - Snapshot storage
 *
 * Keeps the latest CollectedData snapshot in memory and supports version tracking.
 * The MVP stage retains only one snapshot (no multi-version history).
 */
import type { CollectedData, RawProjectInfo } from './types.js';

export interface SnapshotEntry {
	/** Snapshot version (generated by the extension, incremented monotonically) */
	version: number;
	/** Snapshot receive time */
	receivedAt: number;
	/** Extension generation time */
	timestamp: number;
	/** Project information */
	projectUuid: string;
	projectName: string;
	/** Complete data */
	data: CollectedData;
}

/**
 * Snapshot storage (singleton)
 */
export class SnapshotStore {
	private snapshot: SnapshotEntry | null = null;

	/**
	 * Update the snapshot
	 *
	 * Reject version rollback: the new version number must be greater than the current version, otherwise ignore it.
	 */
	update(version: number, projectUuid: string, timestamp: number, data: CollectedData): boolean {
		if (this.snapshot && version <= this.snapshot.version) {
			return false;
		}

		this.snapshot = {
			version,
			receivedAt: Date.now(),
			timestamp,
			projectUuid: projectUuid || data.projectInfo?.projectUuid || '',
			projectName: data.projectInfo?.projectName ?? '',
			data,
		};
		return true;
	}

	/**
	 * Get the current snapshot (returns null when no data is available)
	 */
	get(): SnapshotEntry | null {
		return this.snapshot;
	}

	/**
	 * Get the snapshot version
	 */
	getVersion(): number {
		return this.snapshot?.version ?? 0;
	}

	/**
	 * Get project information
	 */
	getProjectInfo(): RawProjectInfo | undefined {
		return this.snapshot?.data.projectInfo;
	}

	/**
	 * Check whether data is available
	 */
	hasData(): boolean {
		return this.snapshot !== null;
	}

	/**
	 * Reset the version baseline
	 *
	 * Called when a new client connects (hello handshake) so the extension restart can start versioning from 1 again.
	 * Keeps the existing data unchanged and resets only the version number to 0.
	 */
	resetVersionBaseline(): void {
		if (this.snapshot) {
			this.snapshot.version = 0;
		}
	}

	/**
	 * Clear the snapshot
	 */
	clear(): void {
		this.snapshot = null;
	}
}
